# Generated by Django 5.2.8 on 2025-11-23 14:52

import django.db.models.deletion
import smart_selects.db_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aqar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='بواسطة'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listing',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aqar.category'),
        ),
        migrations.AddField(
            model_name='listing',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='governorate', chained_model_field='governorate', on_delete=django.db.models.deletion.CASCADE, to='aqar.city'),
        ),
        migrations.AddField(
            model_name='listing',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='بواسطة'),
        ),
        migrations.AddField(
            model_name='listing',
            name='governorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aqar.governorate'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aqar.listing'),
        ),
        migrations.AddField(
            model_name='listingdocument',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='بواسطة'),
        ),
        migrations.AddField(
            model_name='listingdocument',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aqar.listing'),
        ),
        migrations.AddField(
            model_name='listingfeature',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aqar.feature'),
        ),
        migrations.AddField(
            model_name='listingfeature',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features_values', to='aqar.listing'),
        ),
        migrations.AddField(
            model_name='listingimage',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='aqar.listing'),
        ),
        migrations.AddField(
            model_name='majorzone',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aqar.city'),
        ),
        migrations.AddField(
            model_name='listing',
            name='major_zone',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='city', chained_model_field='city', on_delete=django.db.models.deletion.CASCADE, to='aqar.majorzone'),
        ),
        migrations.AddField(
            model_name='subdivision',
            name='major_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aqar.majorzone'),
        ),
        migrations.AddField(
            model_name='listing',
            name='subdivision',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='major_zone', chained_model_field='major_zone', null=True, on_delete=django.db.models.deletion.CASCADE, to='aqar.subdivision'),
        ),
        migrations.AddField(
            model_name='zonemap',
            name='major_zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='aqar.majorzone'),
        ),
    ]
