# Generated by Django 5.2.8 on 2025-11-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqar', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='floor_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='رقم الدور'),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_finance_eligible',
            field=models.BooleanField(default=False, verbose_name='قابل للتمويل العقاري'),
        ),
        migrations.AddField(
            model_name='listing',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='خط العرض'),
        ),
        migrations.AddField(
            model_name='listing',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='خط الطول'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='الحمامات'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='غرف النوم'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='offer_type',
            field=models.CharField(choices=[('Sale', 'بيع'), ('Rent', 'إيجار')], db_index=True, default='Sale', max_length=10),
        ),
    ]
