# Generated by Django 5.2.8 on 2025-11-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqar', '0003_listing_floor_number_listing_is_finance_eligible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='contract_image',
            field=models.ImageField(blank=True, null=True, upload_to='secure_docs/', verbose_name='صورة العقد'),
        ),
        migrations.AddField(
            model_name='listing',
            name='id_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='secure_docs/', verbose_name='صورة البطاقة'),
        ),
        migrations.AddField(
            model_name='listing',
            name='owner_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='owner_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='listings_videos/', verbose_name='فيديو العقار'),
        ),
    ]
