# Generated by Django 5.2.8 on 2025-11-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqar', '0004_listing_contract_image_listing_id_card_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='custom_map_image',
            field=models.ImageField(blank=True, null=True, upload_to='listings_maps/', verbose_name='صورة مخطط خاصة'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('Pending', 'قيد المراجعة'), ('Available', 'متاح'), ('Sold', 'تم البيع')], db_index=True, default='Pending', max_length=20),
        ),
    ]
