# Generated by Django 5.2.8 on 2025-11-27 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqar', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.TextField(blank=True, null=True, verbose_name='الاهتمامات (شقق، أراضي...)'),
        ),
    ]
