# Generated by Django 5.2.8 on 2025-11-27 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aqar', '0007_profile_interests'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
