# Generated by Django 5.1.4 on 2025-12-16 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqar', '0009_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='icon',
            field=models.CharField(choices=[('CheckCircle2', '✔ علامة صح (افتراضي)'), ('ArrowUpFromLine', '🛗 أسانسير / مصعد'), ('Zap', '⚡ كهرباء / عداد'), ('Wind', '💨 غاز طبيعي'), ('Waves', '💧 مياه / سباحة'), ('Trees', '🌳 حديقة / لاندسكيب'), ('Car', '🚗 جراج / موقف'), ('Wifi', '📶 واي فاي / إنترنت'), ('ShieldCheck', '🛡 أمن وحراسة'), ('Snowflake', '❄ تكييف'), ('Tv', '📺 تلفزيون / دش'), ('Paintbucket', '🎨 تشطيب / ديكور'), ('Dumbbell', '💪 جيم / رياضة'), ('Utensils', '🍽 مطبخ'), ('BedDouble', '🛏 غرفة نوم'), ('Bath', '🛁 حمام')], default='CheckCircle2', max_length=50, verbose_name='شكل الأيقونة'),
        ),
        migrations.AddField(
            model_name='listing',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الشقة'),
        ),
        migrations.AddField(
            model_name='listing',
            name='building_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم العمارة'),
        ),
        migrations.AddField(
            model_name='listing',
            name='project_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المشروع/الكمبوند'),
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الإعلان')),
                ('subtitle', models.CharField(blank=True, max_length=150, null=True, verbose_name='عنوان فرعي (التاج)')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, null=True, unique=True)),
                ('promo_type', models.CharField(choices=[('PROJECT', 'مشروع عقاري (كمبوند/مول)'), ('SERVICE', 'خدمة (تشطيبات/ديكور)'), ('GENERAL', 'إعلان عام (صور وتفاصيل)'), ('LISTING', 'إعلان VIP (ربط بعقار)')], default='GENERAL', max_length=20, verbose_name='نوع الإعلان')),
                ('cover_image', models.ImageField(upload_to='promotions/covers/', verbose_name='صورة الغلاف (للسلايدر)')),
                ('video', models.FileField(blank=True, null=True, upload_to='promotions/videos/', verbose_name='فيديو ترويجي')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='رابط يوتيوب (اختياري)')),
                ('description', models.TextField(blank=True, verbose_name='التفاصيل الكاملة')),
                ('developer_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='المطور العقاري')),
                ('payment_system', models.TextField(blank=True, null=True, verbose_name='نظام السداد (مثال: 10% مقدم والباقي 8 سنوات)')),
                ('delivery_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='ميعاد الاستلام')),
                ('project_features', models.TextField(blank=True, help_text='اكتب كل ميزة في سطر', null=True, verbose_name='مميزات المشروع')),
                ('price_start_from', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='الأسعار تبدأ من')),
                ('location_url', models.URLField(blank=True, null=True, verbose_name='رابط جوجل ماب')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='خط الطول')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='رقم التواصل')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, verbose_name='رقم واتساب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('display_order', models.IntegerField(default=0, verbose_name='ترتيب العرض')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='aqar.listing', verbose_name='العقار المرتبط (للنوع VIP فقط)')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='promotions/gallery/')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='aqar.promotion')),
            ],
        ),
    ]
