# Generated by Django 5.1.4 on 2025-12-16 20:25

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqar', '0010_feature_icon_listing_apartment_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='video',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='listings_videos/', validators=[cloudinary_storage.validators.validate_video], verbose_name='فيديو العقار'),
        ),
    ]
