# Generated by Django 5.1.4 on 2025-12-18 20:43

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqar', '0011_alter_listing_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='developer_logo',
            field=models.ImageField(blank=True, null=True, upload_to='promotions/logos/', verbose_name='لوجو المطور/الشركة'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='video',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='listings_videos/', verbose_name='فيديو العقار'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='video',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='promotions/videos/', verbose_name='فيديو ترويجي'),
        ),
    ]
