# Generated by Django 5.1.4 on 2025-12-19 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqar', '0012_promotion_developer_logo_alter_listing_video_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_image', models.ImageField(upload_to='promotions/before/', verbose_name='صورة قبل')),
                ('after_image', models.ImageField(upload_to='promotions/after/', verbose_name='صورة بعد')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='عنوان (مثال: الريسبشن)')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transformations', to='aqar.promotion')),
            ],
        ),
    ]
