# Generated by Django 5.1.4 on 2025-12-19 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqar', '0013_transformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='master_plan',
            field=models.ImageField(blank=True, null=True, upload_to='promotions/master_plans/', verbose_name='الماستر بلان (Master Plan)'),
        ),
        migrations.CreateModel(
            name='PromotionUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الوحدة (مثال: فيلا تايب A)')),
                ('icon', models.CharField(choices=[('Home', '🏠 بيت / فيلا'), ('Building', '🏢 شقة / استوديو'), ('Store', '🏪 محل تجاري'), ('Briefcase', '💼 مكتب إداري'), ('Stethoscope', '🩺 عيادة طبية'), ('Trees', '🌳 جاردن / دوبلكس'), ('Hotel', '🏨 وحدة فندقية')], default='Home', max_length=50, verbose_name='الأيقونة')),
                ('layout_image', models.ImageField(upload_to='promotions/layouts/', verbose_name='صورة التصميم الداخلي (Layout)')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='aqar.promotion')),
            ],
        ),
    ]
