# Generated by Django 5.1.4 on 2025-12-19 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqar', '0014_promotion_master_plan_promotionunit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionunit',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='promotionunit',
            name='layout_image',
        ),
        migrations.RemoveField(
            model_name='promotionunit',
            name='name',
        ),
        migrations.AddField(
            model_name='promotionunit',
            name='custom_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='عنوان الوحدة (اختياري)'),
        ),
        migrations.AddField(
            model_name='promotionunit',
            name='linked_listing',
            field=models.ForeignKey(blank=True, help_text='اختر العقار الذي يمثل هذا النموذج (فيلا، شقة، إلخ)', null=True, on_delete=django.db.models.deletion.CASCADE, to='aqar.listing', verbose_name='العقار المرتبط (النموذج)'),
        ),
    ]
