# Generated by Django 5.1.4 on 2025-12-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqar', '0015_remove_promotionunit_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='google_maps_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط موقع العقار (Google Maps)'),
        ),
    ]
