# Generated by Django 5.1.4 on 2025-12-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqar', '0016_listing_google_maps_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='options_list',
            field=models.CharField(blank=True, help_text='للنوع الرقمي فقط: اكتب الأرقام مفصولة بفاصلة، مثال: 1,2,3,4,5,6', max_length=200, null=True, verbose_name='الأرقام المقترحة'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='input_type',
            field=models.CharField(choices=[('text', 'نص عادي (Text)'), ('bool', 'نعم/لا (Switch)'), ('number', 'قيمة رقمية (Buttons + Input)')], default='bool', max_length=10, verbose_name='نوع الإدخال'),
        ),
    ]
