# Generated by Django 5.1.4 on 2025-12-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqar', '0017_feature_options_list_alter_feature_input_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='is_quick_filter',
            field=models.BooleanField(default=False, help_text='لو اخترت نعم، الميزة دي هتظهر كزرار في الشريط العلوي (لازم تكون رقمية)', verbose_name='عرض في الفلتر السريع؟'),
        ),
    ]
