# Generated by Django 5.1.4 on 2025-12-22 15:55

import cloudinary_storage.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqar', '0018_feature_is_quick_filter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='call_clicks',
            field=models.PositiveIntegerField(default=0, verbose_name='نقرات الاتصال'),
        ),
        migrations.AddField(
            model_name='listing',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات'),
        ),
        migrations.AddField(
            model_name='listing',
            name='whatsapp_clicks',
            field=models.PositiveIntegerField(default=0, verbose_name='نقرات الواتساب'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='call_clicks',
            field=models.PositiveIntegerField(default=0, verbose_name='نقرات الاتصال'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='clicks_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد النقرات'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='whatsapp_clicks',
            field=models.PositiveIntegerField(default=0, verbose_name='نقرات الواتساب'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='building_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='contract_image',
            field=models.ImageField(blank=True, null=True, upload_to='secure_docs/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='custom_map_image',
            field=models.ImageField(blank=True, null=True, upload_to='listings_maps/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='floor_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='google_maps_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='id_card_image',
            field=models.ImageField(blank=True, null=True, upload_to='secure_docs/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='is_finance_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='project_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='video',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='listings_videos/'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='cover_image',
            field=models.ImageField(upload_to='promotions/covers/'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='delivery_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='developer_logo',
            field=models.ImageField(blank=True, null=True, upload_to='promotions/logos/'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='developer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='location_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='master_plan',
            field=models.ImageField(blank=True, null=True, upload_to='promotions/master_plans/'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='payment_system',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='price_start_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='project_features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='promo_type',
            field=models.CharField(choices=[('PROJECT', 'مشروع عقاري'), ('SERVICE', 'خدمة'), ('GENERAL', 'إعلان عام'), ('LISTING', 'إعلان VIP')], default='GENERAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='subtitle',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='target_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='aqar.listing'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='video',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='promotions/videos/'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='AnalyticsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('VIEW_LISTING', 'مشاهدة عقار'), ('VIEW_PROMO', 'مشاهدة إعلان'), ('CLICK_PROMO', 'ضغط على الإعلان'), ('CLICK_WHATSAPP', 'ضغط واتساب'), ('CLICK_CALL', 'ضغط اتصال'), ('SEARCH', 'بحث')], max_length=20, verbose_name='نوع الحدث')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP الزائر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التوقيت')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aqar.listing', verbose_name='العقار')),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aqar.promotion', verbose_name='الإعلان')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل التحليلات',
                'verbose_name_plural': 'سجلات التحليلات',
                'ordering': ['-created_at'],
            },
        ),
    ]
