# Generated by Django 5.1.4 on 2025-12-24 16:28

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqar', '0020_alter_interaction_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='details_video',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='promotions/details_videos/', verbose_name='فيديو التفاصيل (مرفوع)'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='إذا تم وضع الرابط، سيتم عرضه بدلاً من الفيديو المرفوع في قسم التفاصيل.', null=True, verbose_name='رابط فيديو يوتيوب'),
        ),
    ]
