# Generated by Django 5.1.4 on 2025-12-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqar', '0021_promotion_details_video_promotion_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='لو حطيت رابط هنا، هيتعرض مكان الفيديو المرفوع.', null=True, verbose_name='رابط فيديو يوتيوب'),
        ),
    ]
