# Generated by Django 5.2.8 on 2025-12-01 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqar_core', '0002_user_interests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'إشعار', 'verbose_name_plural': 'الإشعارات'},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='target_interest',
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('System', 'إداري'), ('Listing', 'عقار'), ('Offer', 'عرض')], default='System', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='تمت القراءة؟'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='نص الرسالة'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان الإشعار'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='user',
            name='client_type',
            field=models.CharField(choices=[('Buyer', 'مشترِي'), ('Seller', 'بائع'), ('Investor', 'مستثمر'), ('Marketer', 'مسوق')], default='Buyer', max_length=10, verbose_name='نوع العميل'),
        ),
    ]
