# Generated by Django 5.2.8 on 2025-12-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqar_core', '0003_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.TextField(blank=True, null=True, verbose_name='FCM Token'),
        ),
    ]
