# Generated by Django 5.2.8 on 2025-12-04 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqar_core', '0004_user_fcm_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='المفتاح (كود الإعداد)')),
                ('value', models.CharField(max_length=500, verbose_name='القيمة')),
            ],
            options={
                'verbose_name': 'إعداد عام',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
        migrations.CreateModel(
            name='CustomPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الصفحة')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='رابط الصفحة (Slug)')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='pages_covers/', verbose_name='صورة الغلاف (Header)')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='رابط فيديو (Youtube)')),
                ('body_content', models.TextField(help_text='اكتب هنا التفاصيل الكاملة للصفحة', verbose_name='محتوى الصفحة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط؟')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
            ],
            options={
                'verbose_name': 'صفحة خاصة',
                'verbose_name_plural': 'الصفحات الخاصة (الجوكر)',
            },
        ),
        migrations.CreateModel(
            name='PageFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text='مثال: fas fa-check', max_length=100, verbose_name='كود الأيقونة (FontAwesome)')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان الميزة')),
                ('description', models.CharField(max_length=255, verbose_name='وصف مختصر')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='aqar_core.custompage', verbose_name='الصفحة التابعة لها')),
            ],
            options={
                'verbose_name': 'ميزة',
                'verbose_name_plural': 'مزايا الصفحة',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المشروع/المول')),
                ('developer_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم المطور العقاري')),
                ('location', models.CharField(max_length=255, verbose_name='موقع المشروع')),
                ('description', models.TextField(verbose_name='وصف المشروع التفصيلي')),
                ('cover_image', models.ImageField(upload_to='projects/', verbose_name='صورة الغلاف (Parallax)')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='رابط فيديو دعائي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط؟')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
            ],
            options={
                'verbose_name': 'مشروع / مول (VIP)',
                'verbose_name_plural': 'المشاريع والمولات',
            },
        ),
        migrations.CreateModel(
            name='ProjectUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_type', models.CharField(max_length=100, verbose_name='نوع الوحدة (محل/عيادة/شقة)')),
                ('area', models.FloatField(verbose_name='المساحة (متر)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='السعر الإجمالي')),
                ('status', models.CharField(choices=[('available', 'متاح'), ('sold', 'مباع'), ('reserved', 'محجوز')], default='available', max_length=50, verbose_name='الحالة')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='aqar_core.project', verbose_name='المشروع التابع له')),
            ],
            options={
                'verbose_name': 'وحدة بالمشروع',
                'verbose_name_plural': 'وحدات المشاريع',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان الرئيسي')),
                ('subtitle', models.CharField(blank=True, max_length=300, null=True, verbose_name='العنوان الفرعي')),
                ('image', models.ImageField(upload_to='sliders/', verbose_name='صورة السلايدر')),
                ('target_link', models.CharField(help_text='رابط داخلي أو خارجي يذهب إليه العميل عند الضغط', max_length=500, verbose_name='رابط التوجيه')),
                ('button_text', models.CharField(default='التفاصيل', max_length=50, verbose_name='نص الزر')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط؟')),
                ('display_order', models.IntegerField(default=0, verbose_name='ترتيب الظهور')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
            ],
            options={
                'verbose_name': 'سلايدر (إعلان)',
                'verbose_name_plural': 'السلايدر والإعلانات',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
