# Generated by Django 5.2.8 on 2025-12-04 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqar_core', '0005_sitesetting_custompage_pagefeature_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='pages_gallery/', verbose_name='صورة إضافية للمحتوى')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='تعليق أسفل الصورة (اختياري)')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='aqar_core.custompage', verbose_name='الصفحة التابعة لها')),
            ],
            options={
                'verbose_name': 'صورة محتوى',
                'verbose_name_plural': 'معرض صور المحتوى',
            },
        ),
    ]
