# Generated by Django 5.2.8 on 2025-12-04 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqar_core', '0006_pagegalleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='google_map_url',
            field=models.URLField(blank=True, null=True, verbose_name='رابط جوجل مابس (للتسهيل)'),
        ),
        migrations.AddField(
            model_name='project',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط العرض (Latitude)'),
        ),
        migrations.AddField(
            model_name='project',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط الطول (Longitude)'),
        ),
        migrations.AddField(
            model_name='projectunit',
            name='floor_plan_image',
            field=models.ImageField(blank=True, null=True, upload_to='units_plans/', verbose_name='صورة التقسيمة/الماستر بلان'),
        ),
        migrations.CreateModel(
            name='ProjectGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects_gallery/', verbose_name='صورة للمشروع')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='وصف الصورة (اختياري)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='aqar_core.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'صورة مشروع',
                'verbose_name_plural': 'معرض صور المشروع',
            },
        ),
    ]
