# Generated by Django 5.2.8 on 2025-12-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqar_core', '0007_project_google_map_url_project_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='open_in_new_tab',
            field=models.BooleanField(default=False, verbose_name='فتح في نافذة جديدة؟'),
        ),
    ]
