# Generated by Django 5.1.4 on 2025-12-16 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aqar_core', '0008_slider_open_in_new_tab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custompage',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='pagefeature',
            name='page',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='projectunit',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectgalleryimage',
            name='project',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='PageGalleryImage',
        ),
        migrations.DeleteModel(
            name='CustomPage',
        ),
        migrations.DeleteModel(
            name='PageFeature',
        ),
        migrations.DeleteModel(
            name='ProjectUnit',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectGalleryImage',
        ),
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
