# Generated by Django 5.1.4 on 2025-12-23 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqar_core', '0009_remove_custompage_created_by_remove_pagefeature_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الرسالة')),
                ('message', models.TextField(verbose_name='نص الرسالة')),
                ('target_audience', models.CharField(choices=[('ALL', 'الكل'), ('Buyer', 'المشترين فقط'), ('Seller', 'الملاك/البائعين فقط'), ('Broker', 'السماسرة فقط')], default='ALL', max_length=20, verbose_name='الجمهور المستهدف')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('is_sent', models.BooleanField(default=False, editable=False, verbose_name='تم الإرسال؟')),
            ],
            options={
                'verbose_name': 'إرسال إشعار جماعي',
                'verbose_name_plural': '📣 إرسال إشعارات جماعية',
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False, verbose_name='تمت القراءة؟'),
        ),
        migrations.AlterField(
            model_name='user',
            name='client_type',
            field=models.CharField(choices=[('Buyer', 'مشترِي'), ('Seller', 'بائع'), ('Investor', 'مستثمر'), ('Marketer', 'مسوق')], db_index=True, default='Buyer', max_length=10, verbose_name='نوع العميل'),
        ),
    ]
