# Generated by Django 5.1.4 on 2025-12-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqar_core', '0010_announcement_alter_notification_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_phone', models.CharField(default='01000000000', max_length=20, verbose_name='رقم الاتصال')),
                ('whatsapp_number', models.CharField(default='20100000000', max_length=20, verbose_name='رقم الواتساب (بدون +)')),
            ],
            options={
                'verbose_name': 'إعدادات التواصل',
                'verbose_name_plural': 'إعدادات التواصل',
            },
        ),
    ]
