# Generated by Django 5.1.4 on 2026-01-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqar_core', '0011_contactinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_owner',
            field=models.BooleanField(default=False, help_text='تفعيل هذا الخيار يمنع حذف هذا الحساب نهائياً حتى من قبل المديرين الآخرين.', verbose_name='مالك الموقع'),
        ),
    ]
